// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VenteMobile.Data;

namespace VenteMobile.Migrations
{
    [DbContext(typeof(VenteMobileContext))]
    [Migration("20200414212701_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1");

            modelBuilder.Entity("VenteMobile.Models.Critique", b =>
                {
                    b.Property<int>("CritiqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CritiqueEtoiles")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CritiqueNom")
                        .HasColumnType("TEXT");

                    b.Property<string>("CritiqueText")
                        .HasColumnType("TEXT");

                    b.Property<int>("TelephoneId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CritiqueId");

                    b.HasIndex("TelephoneId");

                    b.ToTable("Critique");

                    b.HasData(
                        new
                        {
                            CritiqueId = 1,
                            CritiqueEtoiles = 6,
                            CritiqueNom = "Alice",
                            CritiqueText = "Le meilleur",
                            TelephoneId = 1
                        },
                        new
                        {
                            CritiqueId = 2,
                            CritiqueEtoiles = 1,
                            CritiqueNom = "Kamal",
                            CritiqueText = "Mauvais",
                            TelephoneId = 2
                        },
                        new
                        {
                            CritiqueId = 3,
                            CritiqueEtoiles = 5,
                            CritiqueNom = "Jean",
                            CritiqueText = "Parfait",
                            TelephoneId = 3
                        },
                        new
                        {
                            CritiqueId = 4,
                            CritiqueEtoiles = 5,
                            CritiqueNom = "Nassin",
                            CritiqueText = "Bien",
                            TelephoneId = 4
                        },
                        new
                        {
                            CritiqueId = 5,
                            CritiqueEtoiles = 6,
                            CritiqueNom = "Maxi",
                            CritiqueText = "Tres bien",
                            TelephoneId = 5
                        },
                        new
                        {
                            CritiqueId = 6,
                            CritiqueEtoiles = 5,
                            CritiqueNom = "Bob",
                            CritiqueText = "j'aime",
                            TelephoneId = 6
                        },
                        new
                        {
                            CritiqueId = 7,
                            CritiqueEtoiles = 5,
                            CritiqueNom = "Mizo",
                            CritiqueText = "Super",
                            TelephoneId = 6
                        },
                        new
                        {
                            CritiqueId = 8,
                            CritiqueEtoiles = 2,
                            CritiqueNom = "Kana",
                            CritiqueText = "pas bien",
                            TelephoneId = 8
                        },
                        new
                        {
                            CritiqueId = 9,
                            CritiqueEtoiles = 3,
                            CritiqueNom = "Annir",
                            CritiqueText = "Probleme ecran",
                            TelephoneId = 8
                        },
                        new
                        {
                            CritiqueId = 10,
                            CritiqueEtoiles = 3,
                            CritiqueNom = "Yannis",
                            CritiqueText = "Probleme affichage",
                            TelephoneId = 7
                        },
                        new
                        {
                            CritiqueId = 11,
                            CritiqueEtoiles = 5,
                            CritiqueNom = "Med",
                            CritiqueText = "Parfait",
                            TelephoneId = 6
                        },
                        new
                        {
                            CritiqueId = 12,
                            CritiqueEtoiles = 5,
                            CritiqueNom = "Basso",
                            CritiqueText = "J'adore",
                            TelephoneId = 4
                        },
                        new
                        {
                            CritiqueId = 13,
                            CritiqueEtoiles = 6,
                            CritiqueNom = "Youri",
                            CritiqueText = "le meilleur de l'annee",
                            TelephoneId = 3
                        },
                        new
                        {
                            CritiqueId = 14,
                            CritiqueEtoiles = 6,
                            CritiqueNom = "Max",
                            CritiqueText = "J'adore",
                            TelephoneId = 1
                        },
                        new
                        {
                            CritiqueId = 15,
                            CritiqueEtoiles = 1,
                            CritiqueNom = "Tony",
                            CritiqueText = "Probleme batterie",
                            TelephoneId = 2
                        },
                        new
                        {
                            CritiqueId = 16,
                            CritiqueEtoiles = 2,
                            CritiqueNom = "Berry",
                            CritiqueText = "Mauvais",
                            TelephoneId = 2
                        },
                        new
                        {
                            CritiqueId = 17,
                            CritiqueEtoiles = 6,
                            CritiqueNom = "Hanid",
                            CritiqueText = "Le meilleur",
                            TelephoneId = 2
                        },
                        new
                        {
                            CritiqueId = 18,
                            CritiqueEtoiles = 3,
                            CritiqueNom = "Pepo",
                            CritiqueText = "Mauvais",
                            TelephoneId = 4
                        },
                        new
                        {
                            CritiqueId = 19,
                            CritiqueEtoiles = 6,
                            CritiqueNom = "Loka",
                            CritiqueText = "Tres bien",
                            TelephoneId = 6
                        },
                        new
                        {
                            CritiqueId = 20,
                            CritiqueEtoiles = 2,
                            CritiqueNom = "Lucie",
                            CritiqueText = "Probleme affichage",
                            TelephoneId = 8
                        },
                        new
                        {
                            CritiqueId = 21,
                            CritiqueEtoiles = 1,
                            CritiqueNom = "Bob",
                            CritiqueText = "Probleme batterie",
                            TelephoneId = 10
                        },
                        new
                        {
                            CritiqueId = 22,
                            CritiqueEtoiles = 1,
                            CritiqueNom = "Yannis",
                            CritiqueText = "Probleme ecran",
                            TelephoneId = 11
                        },
                        new
                        {
                            CritiqueId = 23,
                            CritiqueEtoiles = 5,
                            CritiqueNom = "Vanissa",
                            CritiqueText = "Bien",
                            TelephoneId = 16
                        },
                        new
                        {
                            CritiqueId = 24,
                            CritiqueEtoiles = 3,
                            CritiqueNom = "Youry",
                            CritiqueText = "Probleme tactile",
                            TelephoneId = 16
                        },
                        new
                        {
                            CritiqueId = 25,
                            CritiqueEtoiles = 5,
                            CritiqueNom = "Phelipe",
                            CritiqueText = "Je recommande",
                            TelephoneId = 18
                        });
                });

            modelBuilder.Entity("VenteMobile.Models.Manufacturier", b =>
                {
                    b.Property<int>("ManufacturierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ManufacturierMarque")
                        .HasColumnType("TEXT");

                    b.Property<string>("ManufacturierOrigine")
                        .HasColumnType("TEXT");

                    b.Property<string>("ManufacturierSiteWeb")
                        .HasColumnType("TEXT");

                    b.HasKey("ManufacturierId");

                    b.ToTable("Manufacturier");

                    b.HasData(
                        new
                        {
                            ManufacturierId = 1,
                            ManufacturierMarque = "Apple ",
                            ManufacturierOrigine = "américaine",
                            ManufacturierSiteWeb = "www.apple.com"
                        },
                        new
                        {
                            ManufacturierId = 2,
                            ManufacturierMarque = "Samsung ",
                            ManufacturierOrigine = "coréen",
                            ManufacturierSiteWeb = "www.samsung.com"
                        },
                        new
                        {
                            ManufacturierId = 3,
                            ManufacturierMarque = "Nokia ",
                            ManufacturierOrigine = "finlandaise",
                            ManufacturierSiteWeb = "www.nokia.com"
                        },
                        new
                        {
                            ManufacturierId = 4,
                            ManufacturierMarque = "Blackberry",
                            ManufacturierOrigine = "canadienne",
                            ManufacturierSiteWeb = "www.Blackberry.com"
                        },
                        new
                        {
                            ManufacturierId = 5,
                            ManufacturierMarque = "Huawei",
                            ManufacturierOrigine = "chinois",
                            ManufacturierSiteWeb = "www.huawei.com"
                        },
                        new
                        {
                            ManufacturierId = 6,
                            ManufacturierMarque = "Htc",
                            ManufacturierOrigine = "Taïwan",
                            ManufacturierSiteWeb = "www.htc.com"
                        },
                        new
                        {
                            ManufacturierId = 7,
                            ManufacturierMarque = "LG",
                            ManufacturierOrigine = "coréen",
                            ManufacturierSiteWeb = "www.lg.com"
                        },
                        new
                        {
                            ManufacturierId = 8,
                            ManufacturierMarque = "Sony",
                            ManufacturierOrigine = "japonaise",
                            ManufacturierSiteWeb = "www.sony.com"
                        },
                        new
                        {
                            ManufacturierId = 9,
                            ManufacturierMarque = "Sharp",
                            ManufacturierOrigine = "japonais ",
                            ManufacturierSiteWeb = "www.sharp.com"
                        },
                        new
                        {
                            ManufacturierId = 10,
                            ManufacturierMarque = "UMIDIGI ",
                            ManufacturierOrigine = "chinoise ",
                            ManufacturierSiteWeb = "www.umidigi.com"
                        });
                });

            modelBuilder.Entity("VenteMobile.Models.Telephone", b =>
                {
                    b.Property<int>("TelephoneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ManufacturierId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TelephoneCouleur")
                        .HasColumnType("TEXT");

                    b.Property<int>("TelephoneCout")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TelephoneModel")
                        .HasColumnType("TEXT");

                    b.HasKey("TelephoneId");

                    b.HasIndex("ManufacturierId");

                    b.ToTable("Telephone");

                    b.HasData(
                        new
                        {
                            TelephoneId = 1,
                            ManufacturierId = 10,
                            TelephoneCouleur = "Noir",
                            TelephoneCout = 120,
                            TelephoneModel = "UMIDIGI F2 "
                        },
                        new
                        {
                            TelephoneId = 2,
                            ManufacturierId = 10,
                            TelephoneCouleur = "Bleu",
                            TelephoneCout = 150,
                            TelephoneModel = "UMIDIGI A3S"
                        },
                        new
                        {
                            TelephoneId = 3,
                            ManufacturierId = 1,
                            TelephoneCouleur = "Blanc",
                            TelephoneCout = 450,
                            TelephoneModel = "IPHONE 7 PLUS"
                        },
                        new
                        {
                            TelephoneId = 4,
                            ManufacturierId = 2,
                            TelephoneCouleur = "Blanc",
                            TelephoneCout = 350,
                            TelephoneModel = "Samsung Galaxy S10+"
                        },
                        new
                        {
                            TelephoneId = 5,
                            ManufacturierId = 9,
                            TelephoneCouleur = "Bleu",
                            TelephoneCout = 199,
                            TelephoneModel = "SHARP AQUOS S2"
                        },
                        new
                        {
                            TelephoneId = 6,
                            ManufacturierId = 1,
                            TelephoneCouleur = "Gris",
                            TelephoneCout = 900,
                            TelephoneModel = "iphone 11 pro"
                        },
                        new
                        {
                            TelephoneId = 7,
                            ManufacturierId = 7,
                            TelephoneCouleur = "Blanc",
                            TelephoneCout = 90,
                            TelephoneModel = "LG G8X"
                        },
                        new
                        {
                            TelephoneId = 8,
                            ManufacturierId = 10,
                            TelephoneCouleur = "Bleu",
                            TelephoneCout = 99,
                            TelephoneModel = "UMIDIGI A3S"
                        },
                        new
                        {
                            TelephoneId = 9,
                            ManufacturierId = 5,
                            TelephoneCouleur = "Gris",
                            TelephoneCout = 89,
                            TelephoneModel = "HUAWEI P30 Pro"
                        },
                        new
                        {
                            TelephoneId = 10,
                            ManufacturierId = 5,
                            TelephoneCouleur = "",
                            TelephoneCout = 199,
                            TelephoneModel = "Huawei P Smart"
                        },
                        new
                        {
                            TelephoneId = 11,
                            ManufacturierId = 5,
                            TelephoneCouleur = "Blanc",
                            TelephoneCout = 149,
                            TelephoneModel = "Huawei Y5 "
                        },
                        new
                        {
                            TelephoneId = 12,
                            ManufacturierId = 1,
                            TelephoneCouleur = "Noir",
                            TelephoneCout = 840,
                            TelephoneModel = "iPhone X"
                        },
                        new
                        {
                            TelephoneId = 13,
                            ManufacturierId = 4,
                            TelephoneCouleur = "Gris",
                            TelephoneCout = 250,
                            TelephoneModel = "Blackberry Key2"
                        },
                        new
                        {
                            TelephoneId = 14,
                            ManufacturierId = 7,
                            TelephoneCouleur = "Bleu",
                            TelephoneCout = 129,
                            TelephoneModel = "LG K30"
                        },
                        new
                        {
                            TelephoneId = 15,
                            ManufacturierId = 1,
                            TelephoneCouleur = "Noir",
                            TelephoneCout = 589,
                            TelephoneModel = " iPhone 8"
                        },
                        new
                        {
                            TelephoneId = 16,
                            ManufacturierId = 3,
                            TelephoneCouleur = "Noir",
                            TelephoneCout = 89,
                            TelephoneModel = "NOKIA 5.1 Global "
                        },
                        new
                        {
                            TelephoneId = 17,
                            ManufacturierId = 2,
                            TelephoneCouleur = "Noir",
                            TelephoneCout = 249,
                            TelephoneModel = "Samsung Galaxy A70 "
                        },
                        new
                        {
                            TelephoneId = 18,
                            ManufacturierId = 10,
                            TelephoneCouleur = "Gris",
                            TelephoneCout = 129,
                            TelephoneModel = "UMIDIGI A3X "
                        });
                });

            modelBuilder.Entity("VenteMobile.Models.TelephoneVendeur", b =>
                {
                    b.Property<int>("TelephoneId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VendeurId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TelephoneId", "VendeurId");

                    b.HasIndex("VendeurId");

                    b.ToTable("TelephoneVendeur");
                });

            modelBuilder.Entity("VenteMobile.Models.Vendeur", b =>
                {
                    b.Property<int>("VendeurId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("VendeurAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("VendeurNoTel")
                        .HasColumnType("TEXT");

                    b.Property<string>("VendeurNom")
                        .HasColumnType("TEXT");

                    b.HasKey("VendeurId");

                    b.ToTable("Vendeur");

                    b.HasData(
                        new
                        {
                            VendeurId = 1,
                            VendeurAddress = "1263 Boulevard Jolibourg #107, Laval, QC H7Y 1Z8",
                            VendeurNoTel = "(514) 865-6220",
                            VendeurNom = "Amazon"
                        },
                        new
                        {
                            VendeurId = 2,
                            VendeurAddress = "2995 Boulevard Moïse-Vincent, Saint-Hubert, QC J3Z 1K2",
                            VendeurNoTel = "(450) 710-2037",
                            VendeurNom = "Best Buy"
                        },
                        new
                        {
                            VendeurId = 3,
                            VendeurAddress = "1040 Boulevard du Grand Héron, Saint-Jérôme, QC J7Y 5K8",
                            VendeurNoTel = "(450) 420-1464",
                            VendeurNom = "KGE Électronique"
                        },
                        new
                        {
                            VendeurId = 4,
                            VendeurAddress = "401 Boul Labelle Unit M-20, Rosemère, Quebec J7A 3T2",
                            VendeurNoTel = "(514) 376-1740",
                            VendeurNom = "Addison Électronique"
                        },
                        new
                        {
                            VendeurId = 5,
                            VendeurAddress = "3075 Chemin d'Oka local 110, Sainte-Marthe-sur-le-Lac, Quebec J0N 1P0",
                            VendeurNoTel = "450) 766-2300",
                            VendeurNom = "MONTREAL INFORMATIQUE"
                        },
                        new
                        {
                            VendeurId = 6,
                            VendeurAddress = " 8480 Boulevard Leduc Unit 100, Brossard, Quebec J4Y 0K7",
                            VendeurNoTel = "(450) 461-1557",
                            VendeurNom = "CIPC"
                        },
                        new
                        {
                            VendeurId = 7,
                            VendeurAddress = "149 Boulevard Desjardins, Maniwaki, QC J9E 2C9",
                            VendeurNoTel = "(450) 781-2030",
                            VendeurNom = "Dantech"
                        },
                        new
                        {
                            VendeurId = 8,
                            VendeurAddress = "3908 Rue Saint-Denis, Montréal, QC H2W 2M4",
                            VendeurNoTel = "(450) 744-0444",
                            VendeurNom = "Accès Electronique"
                        },
                        new
                        {
                            VendeurId = 9,
                            VendeurAddress = "175 Chemin Jean-Adam, Saint-Sauveur, QC J0R 1R6",
                            VendeurNoTel = "(450) 436-4883",
                            VendeurNom = "The Source"
                        },
                        new
                        {
                            VendeurId = 10,
                            VendeurAddress = "1025 Boulevard Lachapelle, Saint-Jérôme, QC J7Z 7M4",
                            VendeurNoTel = "",
                            VendeurNom = "Top Laptop"
                        },
                        new
                        {
                            VendeurId = 11,
                            VendeurAddress = "1800 Avenue Auguste, Longueuil, QC J4V 3R4",
                            VendeurNoTel = "(450) 443-3817",
                            VendeurNom = "Lozeau"
                        },
                        new
                        {
                            VendeurId = 12,
                            VendeurAddress = " 4526 Rue Saint-Denis, Montréal, QC H2J 2L3",
                            VendeurNoTel = "(514) 495-4636",
                            VendeurNom = "Dumoulin"
                        },
                        new
                        {
                            VendeurId = 13,
                            VendeurAddress = "145 Montée Masson, Mascouche, QC J7K 3B4",
                            VendeurNoTel = "(514) 849-2999",
                            VendeurNom = "SONXPLUS"
                        },
                        new
                        {
                            VendeurId = 14,
                            VendeurAddress = "319 Rue Notre-Dame, Repentigny, QC J6A 2S1",
                            VendeurNoTel = "(450) 704-4400",
                            VendeurNom = "Centre Hi-Fi"
                        });
                });

            modelBuilder.Entity("VenteMobile.Models.VendeurManufacturier", b =>
                {
                    b.Property<int>("ManufacturierId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VendeurId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ManufacturierId", "VendeurId");

                    b.HasIndex("VendeurId");

                    b.ToTable("VendeurManufacturier");
                });

            modelBuilder.Entity("VenteMobile.Models.Critique", b =>
                {
                    b.HasOne("VenteMobile.Models.Telephone", "Telephone")
                        .WithMany("Critiques")
                        .HasForeignKey("TelephoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VenteMobile.Models.Telephone", b =>
                {
                    b.HasOne("VenteMobile.Models.Manufacturier", "Manufacturier")
                        .WithMany("Telephones")
                        .HasForeignKey("ManufacturierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VenteMobile.Models.TelephoneVendeur", b =>
                {
                    b.HasOne("VenteMobile.Models.Telephone", "Telephone")
                        .WithMany("TelephonesVendeurs")
                        .HasForeignKey("TelephoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VenteMobile.Models.Vendeur", "Vendeur")
                        .WithMany("TelephonesVendeurs")
                        .HasForeignKey("VendeurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VenteMobile.Models.VendeurManufacturier", b =>
                {
                    b.HasOne("VenteMobile.Models.Manufacturier", "Manufacturier")
                        .WithMany("VendeursManufacturiers")
                        .HasForeignKey("ManufacturierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VenteMobile.Models.Vendeur", "Vendeur")
                        .WithMany("VendeursManufacturiers")
                        .HasForeignKey("VendeurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
